# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_A5.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import numpy as np
import cv2 
from PyQt5.QtWidgets import QFileDialog 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(732, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 310, 161, 71))
        self.label.setStyleSheet("border-image: url(:/cct/logo.png);\n"
"background-image: url(:/cct/logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 230, 121, 61))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 10, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 90, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 140, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 60, 501, 311))
        self.label_3.setStyleSheet("QLabel {\n"
"    border: 2px solid black;   /* Borde negro de 2px */\n"
"    border-radius: 8px;        /* Opcional: esquinas redondeadas */\n"
"    background-color: white;   /* Opcional: fondo blanco */\n"
"}\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 732, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.ruta_imagen = None
        self.pushButton.clicked.connect(self.cargar_imagen)
        self.pushButton_2.clicked.connect(self.dibujar_contornos)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Sara Barreto <br/>Jeisson Avila<br/>Paola Vaquiro</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Generar contornos de una imagen</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Cargar Imagen"))
        self.pushButton_2.setText(_translate("MainWindow", "Dibujar contornos"))

    def cargar_imagen(self):
        opciones = QFileDialog.Options()
        archivo, _ = QFileDialog.getOpenFileName(
            None, 
            "Seleccionar Imagen", 
            "", 
            "Archivos de Imagen (*.png *.jpg *.jpeg *.bmp)", 
            options=opciones
        )
        if archivo:
            self.ruta_imagen = archivo
            pixmap = QtGui.QPixmap(archivo).scaled(
                self.label_3.width(), 
                self.label_3.height(),
                QtCore.Qt.KeepAspectRatio, 
                QtCore.Qt.SmoothTransformation
            )
            self.label_3.setPixmap(pixmap)

    def dibujar_contornos(self):
        if self.ruta_imagen is None:
            return  # No hay imagen cargada

        img = cv2.imread(self.ruta_imagen, cv2.IMREAD_GRAYSCALE)
        if img is None:
            return

        bordes = cv2.Canny(img, 100, 200)
        img_rgb = cv2.cvtColor(bordes, cv2.COLOR_GRAY2RGB)

        h, w, ch = img_rgb.shape
        bytes_per_line = ch * w
        qimg = QtGui.QImage(img_rgb.data, w, h, bytes_per_line, QtGui.QImage.Format_RGB888)
        pixmap = QtGui.QPixmap.fromImage(qimg).scaled(
            self.label_3.width(), 
            self.label_3.height(),
            QtCore.Qt.KeepAspectRatio, 
            QtCore.Qt.SmoothTransformation
        )
        self.label_3.setPixmap(pixmap)

import logo_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

