# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_A1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math   # <--- Importamos librería matemática


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 403)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 150, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 180, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 210, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 240, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 270, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(150, 150, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 180, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(150, 210, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(150, 240, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(150, 270, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(150, 300, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(290, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(290, 160, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 201, 101))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 111, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 90, 121, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(290, 300, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(290, 260, 111, 21))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # ---- Conexión de botones con funciones ----
        self.pushButton.clicked.connect(self.Suma)
        self.pushButton_2.clicked.connect(self.Resta)
        self.pushButton_3.clicked.connect(self.Multiplicacion)
        self.pushButton_4.clicked.connect(self.Cociente)
        self.pushButton_5.clicked.connect(self.Residuo)
        self.pushButton_6.clicked.connect(self.Seno)
        self.pushButton_7.clicked.connect(self.Coseno)
        self.pushButton_8.clicked.connect(self.Tangente)
        self.pushButton_9.clicked.connect(self.Secante)
        self.pushButton_10.clicked.connect(self.Cotangente)
        self.pushButton_11.clicked.connect(self.Cosecante)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "SUMA"))
        self.pushButton_2.setText(_translate("MainWindow", "RESTA"))
        self.pushButton_3.setText(_translate("MainWindow", "MULTIPLICACION"))
        self.pushButton_4.setText(_translate("MainWindow", "COCIENTE"))
        self.pushButton_5.setText(_translate("MainWindow", "RESIDUO"))
        self.pushButton_6.setText(_translate("MainWindow", "SENO"))
        self.pushButton_7.setText(_translate("MainWindow", "COSENO"))
        self.pushButton_8.setText(_translate("MainWindow", "TANGENTE"))
        self.pushButton_9.setText(_translate("MainWindow", "SECANTE"))
        self.pushButton_10.setText(_translate("MainWindow", "COTAGENTE"))
        self.pushButton_11.setText(_translate("MainWindow", "COSECANTE"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Sara Barreto </span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Jeisson Avila </span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Paola Vaquiro </span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_6.setText(_translate("MainWindow", "RESULTADO"))

    def getValues(self):
        try:
            v1 = int(self.textEdit_2.toPlainText())
        except:
            v1 = 0
        try:
            v2 = int(self.textEdit.toPlainText())
        except:
            v2 = 0
        return v1, v2

    def showResult(self, result):
        self.label_5.setText(str(result))

    def Suma(self):
        v1, v2 = self.getValues()
        self.showResult(v1 + v2)

    def Resta(self):
        v1, v2 = self.getValues()
        self.showResult(v1 - v2)

    def Multiplicacion(self):
        v1, v2 = self.getValues()
        self.showResult(v1 * v2)

    def Cociente(self):
        v1, v2 = self.getValues()
        if v2 != 0:
            self.showResult(v1 / v2)
        else:
            self.showResult("Error")

    def Residuo(self):
        v1, v2 = self.getValues()
        if v2 != 0:
            self.showResult(v1 % v2)
        else:
            self.showResult("Error")

    def Seno(self):
        v1, _ = self.getValues()
        self.showResult(round(math.sin(math.radians(v1)), 4))

    def Coseno(self):
        v1, _ = self.getValues()
        self.showResult(round(math.cos(math.radians(v1)), 4))

    def Tangente(self):
        v1, _ = self.getValues()
        try:
            self.showResult(round(math.tan(math.radians(v1)), 4))
        except:
            self.showResult("Error")

    def Secante(self):
        v1, _ = self.getValues()
        try:
            self.showResult(round(1 / math.cos(math.radians(v1)), 4))
        except:
            self.showResult("Error")

    def Cotangente(self):
        v1, _ = self.getValues()
        try:
            self.showResult(round(1 / math.tan(math.radians(v1)), 4))
        except:
            self.showResult("Error")

    def Cosecante(self):
        v1, _ = self.getValues()
        try:
            self.showResult(round(1 / math.sin(math.radians(v1)), 4))
        except:
            self.showResult("Error")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
