# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_A3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(629, 514)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Logo
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 410, 161, 71))
        self.label.setStyleSheet("")
        self.label.setMidLineWidth(-4)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logo.png"))  # Imagen directa
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        # Nombres
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 420, 121, 61))
        self.label_2.setObjectName("label_2")

        # ComboBox de robots
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(300, 60, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")   # índice 0 vacío
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("Robot Cartesiano")
        self.comboBox.addItem("Robot Esférico")
        self.comboBox.addItem("Robot Cilíndrico")

        # Etiquetas de título
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 50, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 10, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        # Frame para imagen del robot
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(240, 100, 361, 311))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        # Imagen del diagrama
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 341, 291))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        # Descripción del robot
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 150, 171, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 629, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Conexión del comboBox
        self.comboBox.currentIndexChanged.connect(self.mostrar_robot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", 
            "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">"
            "Sara Barreto <br/>Jeisson Avila<br/>Paola Vaquiro</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", 
            "<html><head/><body><p><span style=\" font-size:12pt;\">Escoja el tipo de robot</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", 
            "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Tipos de robots y sus articulaciones</span></p></body></html>"))

    # ================= Lógica para mostrar los robots =================
    def mostrar_robot(self, index):
        if index == 1:  # Robot Cartesiano
            self.label_3.setText("Robot Cartesiano:\n\n3 articulaciones prismáticas\n(Movimientos en X, Y, Z).")
            pixmap = QtGui.QPixmap("cartesiano.png")
            self.label_4.setPixmap(pixmap.scaled(300, 250, QtCore.Qt.KeepAspectRatio))

        elif index == 2:  # Robot Esférico
            self.label_3.setText("Robot Esférico:\n\n2 articulaciones rotacionales\n+ 1 prismática.")
            pixmap = QtGui.QPixmap("esferico.png")
            self.label_4.setPixmap(pixmap.scaled(300, 250, QtCore.Qt.KeepAspectRatio))

        elif index == 3:  # Robot Cilíndrico
            self.label_3.setText("Robot Cilíndrico:\n\n1 articulación rotacional\n+ 2 prismáticas.")
            pixmap = QtGui.QPixmap("cilindrico.png")
            self.label_4.setPixmap(pixmap.scaled(300, 250, QtCore.Qt.KeepAspectRatio))

        else:
            self.label_3.clear()
            self.label_4.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
